### ISSUE TITLE
请问安卓手机termux有支持qemu的加速器吗？

### ISSUE THREAD

**Issue by ghost** [Uchiha-Peng/QEMU-ARM64-Debian-Ubuntu#1]
```
        我看了您的文章，心里非常开心，因为，我最近正在寻求手机架构上安装完整的linux系统，
但是模拟x86_64架构又太慢，arm64架构的aarch64我又模拟不出来，直到看到了您的文章，我才瞬间通畅。
        当然，这条信息不是个问题，只是，想向您询问，有没有适合安卓手机termux armv8架构的qemu加速器，
上网上查了好多，官网页浏览了不少，加速器大部分都是PC端CPU的专属，手机端的CPU架构几乎就没有加
速器的描述，>_<，如果知道请告知，真的谢谢大佬了。
```

**Comment by Uchiha-Peng** [comment]
> ```
>         我看了您的文章，心里非常开心，因为，我最近正在寻求手机架构上安装完整的linux系统，
> 但是模拟x86_64架构又太慢，arm64架构的aarch64我又模拟不出来，直到看到了您的文章，我才瞬间通畅。
>         当然，这条信息不是个问题，只是，想向您询问，有没有适合安卓手机termux armv8架构的qemu加速器，
> 上网上查了好多，官网页浏览了不少，加速器大部分都是PC端CPU的专属，手机端的CPU架构几乎就没有加
> 速器的描述，>_<，如果知道请告知，真的谢谢大佬了。
> ```

不太清楚啊，这个是很久之前弄的，每次进入系统需要手动引导，比较麻烦，后来我发现了一种更好的办法，无需手动引导，就是用cloud image，我写过一个教程，你自己看看。 https://juejin.cn/post/6905654257782161422  我也做过一个镜像，可以在x86的机器上用docker运行arm的容器。其实现在我已经实现了在手机上运行完整的linux，有个叫mobian/droidbian的项目，可以在手机上运行debian linux，postmarket os也可以。当然，还有大名鼎鼎的ubuntu touch

**Comment by ghost** [comment]
谢谢大佬，我好好研究研究
